---

- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 86400

  tasks:
    - include: tasks/packages.yml
    - include: tasks/software.yml
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/users.yml
    - include: tasks/cronjobs.yml
