---

#
# Shortcuts
#

- name: Terminal shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/terminal"
    value: "['<Super>t']"

- name: File browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>f']"

- name: Web browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "['<Super>w']"

#
# Date and time
#

- name: Automatic timezone
  dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"

- name: Clock show date
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: Clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

