---

- name: Install packages
  package:
    state: present
    name:
      - ca-certificates
      - curl
      - git
      - gitk
      - gnome-tweaks
      - htop
      - httpie
      - libnotify-bin # "alert" alias (notify-send)
      - mc
      - nano
      - neofetch
      - python3-psutil # required by gnome tasks
      - tig
      - tree
      - unzip
      - vim
      - wget
      - zip

- name: Uninstall packages
  package:
    state: absent
    name: []
