---

- name: Install packages
  package:
    state: present
    name:
      - mc
      - htop
      - vim
      - nano
      - neofetch
      - git
      - tig
      - gitk
      - zip
      - unzip
      - curl
      - wget
      - python3-psutil # required by gnome tasks
      - gnome-tweaks
      - tree

- name: Uninstall packages
  package:
    state: absent
    name: []
